name: Continuous Integration Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - production
      - develop
      - 'epic/**'

# Esto cancela ejecuciones antiguas si subes un nuevo commit rápido al mismo PR
concurrency:
  group: ci-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-pipeline:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Obligatorio para que Commitlint pueda leer el historial

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ajusta esto si usan otra versión de Node
          cache: 'pnpm'

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Commits (Commitlint)
        run: bun x commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Architecture Lint (ls-lint)
        run: bun run ls-lint

      - name: Code Linting (ESLint)
        run: bun run lint

      # Etiquetado Automático de Carpetas
      - name: Add Folder Labels
        uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true